{
 "title": "AirGradient Insights",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(airgradient_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "airgradient_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((airgradient_temperature_celsius{instance=\"$instance\"} * 9 / 5) + 32[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum by(instance)(avg_over_time(airgradient_temperature_celsius{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "title": "TVOC Index",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance)(airgradient_tvoc_index{instance=\"$instance\"})",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "targets": [
    { "expr": "airgradient_info", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "targets": [
    { "expr": "airgradient_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(airgradient_humidity_percent{instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum by(instance)(avg_over_time(airgradient_humidity_percent{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "title": "CO2 PPM",
   "type": "timeseries",
   "description": "The amount of CO2 in PPM",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "sum by(instance)(airgradient_co2_ppm{instance=\"$instance\"})",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "targets": [
    { "expr": "airgradient_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NOx Index",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(instance)(airgradient_nox_index{instance=\"$instance\"})",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  { "title": "PM graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "PM1 μg/m3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "sum by(instance)(airgradient_pm1_ugm3{instance=\"$instance\"})",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "title": "PM2.5 μg/m3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "sum by(instance)(airgradient_pm2d5_ugm3{instance=\"$instance\"})",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "title": "PM10 μg/m3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "sum by(instance)(airgradient_pm10_ugm3{instance=\"$instance\"})",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "title": "PM0.3 count per deciliter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum by(instance)(airgradient_pm0d3_p100ml{instance=\"$instance\"})",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  }
 ]
}