{
 "title": "o11y-home",
 "tags": [
  "status:production",
  "owner:o11y"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics_datasource", "label": "Metrics Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "VMAgent Details :: Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Samples Rate",
   "type": "timeseries",
   "description": "Shows in/out [samples](https://docs.victoriametrics.com/keyconcepts/#raw-samples) rate including push and pull models. \n\nThe out-rate could be different to in-rate because of replication or additional timeseries added by vmagent for every scraped target.\n\nClick on the line and choose Drilldown to show CPU usage per instance\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"vmagent_rows_inserted_total|vm_promscrape_scraped_samples_sum\", job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job)",
     "legendFormat": "{{job}} / in"
    },
    {
     "expr": "sum(rate(vmagent_remotewrite_block_size_rows_sum{job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job)",
     "legendFormat": "{{job}} / out"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "description": "Errors rate shows rate for multiple metrics that track possible errors in vmagent, such as network or parsing errors.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vmagent_http_request_errors_total{job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job, protocol) > 0",
     "legendFormat": "{{job}} (requests: {{protocol}})"
    },
    {
     "expr": "sum(rate(vm_protoparser_read_errors_total{job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job, type) > 0",
     "legendFormat": "{{job}} (parse: {{type}})"
    },
    {
     "expr": "sum(rate(vm_ingestserver_request_errors_total{job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job, type) > 0",
     "legendFormat": "{{job}} (ingest: {{type}})"
    },
    {
     "expr": "sum(rate(vm_protoparser_unmarshal_errors_total{job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job, type) > 0",
     "legendFormat": "{{job}} (unmarshal: {{type}})"
    },
    {
     "expr": "sum(rate(vm_promscrape_dial_errors_total{job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job) > 0",
     "legendFormat": "{{job}} (scrape dial)"
    }
   ]
  },
  {
   "title": "Persistent Queue Size",
   "type": "timeseries",
   "description": "Persistent queue size shows size of pending samples in bytes which hasn't been flushed to remote storage yet. \nIncreasing of value might be a sign of connectivity issues. In such cases, vmagent starts to flush pending data on disk with attempt to send it later once connection is restored.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(vm_persistentqueue_bytes_pending{job_origin=\"vmagent-scraper\"}) by(job) > 0",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Log Errors (30m)",
   "type": "timeseries",
   "description": "Shows number of generated  error messages in  logs over last 30m. Non-zero value may be a sign of connectivity or misconfiguration errors.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(vm_log_messages_total{job_origin=\"vmagent-scraper\", level!=\"info\"}[30m])) by(job) > 0",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Click on the line and choose Drilldown to show CPU usage per instance",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n    rate(process_cpu_seconds_total{job_origin=\"vmagent-scraper\"}[$__rate_interval])\n    /\n    vm_available_cpu_cores{job_origin=\"vmagent-scraper\"}\n) by(job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "description": "Shows the rate of requests served by vmagent HTTP server.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vmagent_http_requests_total{job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job, path) > 0",
     "legendFormat": "{{job}} ({{path}})"
    }
   ]
  },
  { "title": "VMAgent Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Samples Rate",
   "type": "timeseries",
   "description": "Shows in/out [samples](https://docs.victoriametrics.com/keyconcepts/#raw-samples) rate including push and pull models. \n\nThe out-rate could be different to in-rate because of replication or additional timeseries added by vmagent for every scraped target.\n\nClick on the line and choose Drilldown to show CPU usage per instance\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"vmagent_rows_inserted_total|vm_promscrape_scraped_samples_sum\", job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job)",
     "legendFormat": "{{job}} / in"
    },
    {
     "expr": "sum(rate(vmagent_remotewrite_block_size_rows_sum{job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job)",
     "legendFormat": "{{job}} / out"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "description": "Errors rate shows rate for multiple metrics that track possible errors in vmagent, such as network or parsing errors.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vmagent_http_request_errors_total{job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job, protocol) > 0",
     "legendFormat": "requests:{{protocol}} ({{job}})"
    },
    {
     "expr": "sum(rate(vm_protoparser_read_errors_total{job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job, type) > 0",
     "legendFormat": "parse: {{type}} ({{job}})"
    },
    {
     "expr": "sum(rate(vm_ingestserver_request_errors_total{job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job, type) > 0",
     "legendFormat": "ingest: {{type}} ({{job}})"
    },
    {
     "expr": "sum(rate(vm_protoparser_unmarshal_errors_total{job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job, type) > 0",
     "legendFormat": "unmarshal: {{type}} ({{job}})"
    },
    {
     "expr": "# How many times vmagent failed to establish a TCP connection to a scrape target\nsum(rate(vm_promscrape_dial_errors_total{job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job) > 0",
     "legendFormat": "scrape dial ({{job}})"
    }
   ]
  },
  {
   "title": "Persistent Queue Size",
   "type": "timeseries",
   "description": "Persistent queue size shows size of pending samples in bytes which hasn't been flushed to remote storage yet. \nIncreasing of value might be a sign of connectivity issues. In such cases, vmagent starts to flush pending data on disk with attempt to send it later once connection is restored.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(vm_persistentqueue_bytes_pending{job_origin=\"vmagent-scraper\"} > 0) by(job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Log Errors (30m)",
   "type": "timeseries",
   "description": "Shows number of generated  error messages in  logs over last 30m. Non-zero value may be a sign of connectivity or misconfiguration errors.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(vm_log_messages_total{job_origin=\"vmagent-scraper\", level!=\"info\"}[30m]) > 0) by(job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(vm_app_version) by(job, short_version)"
    },
    {
     "expr": "sum(vm_app_uptime_seconds) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "vmagent-scraper :: Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Samples Scraped/s",
   "type": "stat",
   "description": "Shows rate of [samples](https://docs.victoriametrics.com/keyconcepts/#raw-samples) scraped from configured targets.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vm_promscrape_scraped_samples_sum{job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job_origin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Targets Scraped/s",
   "type": "stat",
   "description": "Shows number of targets scraped per second.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vm_promscrape_scrapes_total{job=\"vmagent-scraper\", job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job_origin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Targets",
   "type": "stat",
   "description": "Shows total configured scrape targets in state `up` or `down`.\n",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(vm_promscrape_targets{job_origin=\"vmagent-scraper\", status=\"up\"}) by(job_origin)",
     "legendFormat": "up"
    },
    {
     "expr": "sum(vm_promscrape_targets{job_origin=\"vmagent-scraper\", status=\"down\"}) by(job_origin)",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Scrape Targets Down",
   "type": "bargauge",
   "description": "Shows total configured scrape targets in state `down`.\n",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_promscrape_targets{job_origin=\"vmagent-scraper\", status=\"down\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "vmagent-scraper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Samples Scraped/s",
   "type": "stat",
   "description": "Shows rate of [samples](https://docs.victoriametrics.com/keyconcepts/#raw-samples) scraped from configured targets.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vm_promscrape_scraped_samples_sum{job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job_origin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Targets Scraped/s",
   "type": "stat",
   "description": "Shows number of targets scraped per second.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vm_promscrape_scrapes_total{job=\"vmagent-scraper\", job_origin=\"vmagent-scraper\"}[$__rate_interval])) by(job_origin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Targets",
   "type": "stat",
   "description": "Shows total configured scrape targets in state `up` or `down`.\n",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(vm_promscrape_targets{job_origin=\"vmagent-scraper\", status=\"up\"}) by(job_origin)",
     "legendFormat": "up"
    },
    {
     "expr": "sum(vm_promscrape_targets{job_origin=\"vmagent-scraper\", status=\"down\"}) by(job_origin)",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Scrape Timeout",
   "type": "timeseries",
   "description": "Shows how close the scrape is to the configured timeout",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds / on(job, instance) group_left() scrape_timeout_seconds",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "vmruler :: Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dropped Remote Writes",
     "type": "timeseries",
     "description": "Increments only when vmalert gives up on some rows and drops them from its remote-write queue. Typical causes:\n- Remote-write queue is full\n- Sustained downstream outage\n- remoteWrite.maxQueueSize too small\n- Ingest rate > egress rate for too long",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vmalert_remotewrite_dropped_rows_total{job_origin=\"vmagent-scraper\"} > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Remote Writes",
     "type": "timeseries",
     "description": "Failed remote writes will retry until success or until the queue overflows. Typical causes:\n- Remote endpoint unreachable / TCP failure\n- Non-2xx HTTP response\n- TLS / auth errors\n- Context deadline exceeded (timeout)",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vmalert_remotewrite_errors_total{job_origin=\"vmagent-scraper\"} > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed vmruler Notifications",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(addr) (rate(vmalert_alerts_send_errors_total{job_origin=\"vmagent-scraper\"}[10m]) > 0)",
       "legendFormat": "{{addr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "vmruler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed VM Remote Writes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vmalert_remotewrite_errors_total{job_origin=\"vmagent-scraper\"} > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed VM Remote Writes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(addr)(vmalert_alerts_send_errors_total{job_origin=\"vmagent-scraper\"} > 0)",
       "legendFormat": "{{addr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "victoria-metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true
  }
 ]
}