{
 "title": "service-health",
 "tags": [
  "owner:srp",
  "status:production"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics_datasource", "label": "Metrics Datasource", "query": "prometheus" },
   { "name": "logs_datasource", "label": "Logs Datasource", "query": "loki" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(container_last_seen,container_label_com_docker_compose_service)"
    }
   },
   {
    "name": "service_filter",
    "query": {
     "query": "label_values(container_last_seen,container_label_com_docker_compose_service)"
    }
   },
   { "name": "search_message" },
   {
    "name": "level_filter",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "O11y Service Health Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<table>\n  <tbody style=\"font-family: 'Roboto Mono', monospace; font-size: 0.75rem\">\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Service</td>\n      <td>{{data.0.name}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Image</td>\n      <td>{{data.0.image}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Health</td>\n      <td style=\"color: {{#if (eq data.0.health_check 1)}}#4CAF50{{else}}#F44336{{/if}}\">\n        {{#if (eq data.0.health_check 1)}}Healthy{{else}}Unhealthy{{/if}}\n      </td>\n    </tr>\n  </tbody>\n</table>"
   },
   "targets": [
    {
     "expr": "container_last_seen{name=\"$service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_health_state{name=\"$service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$service Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (container_health_state{name=\"$service\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$service Uptime",
   "type": "stat",
   "description": "Determined by _consul_ uptime.",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name)(time() - container_start_time_seconds{name=\"$service\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$service Health History",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum by(name) (container_health_state{name=\"$service\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Service Health",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (name) (container_health_state)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum by(name) (\n    (time() - container_start_time_seconds)/3600\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(container_last_seen) by (name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restarting Services",
   "type": "table",
   "description": "Services that have restarted 3 or more times over the last hour",
   "gridPos": { "h": 10, "w": 6, "x": 10, "y": 4 },
   "targets": [
    {
     "expr": "sort_desc(count by(name) (count_over_time(container_last_seen[1h]))) >= 3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
     "options": {
      "content": "<table>\n  <tbody style=\"font-family: 'Roboto Mono', monospace; font-size: 0.75rem\">\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Log Count</td>\n      <td>{{log_count}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Log Rate (log/s)</td>\n      <td>{{log_rate}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Service Logs</td>\n      <td>\n        <a style=\"color: #6e9fff\" ;\n          href=\"https://grafana.int.coreweave.com/d/ee2kn1qtyfldse/services-log-explorer?orgId=1&var-cluster={{ variable \"cluster\" }}&var-container_name={{ variable \"service\" }}\">\n          Dashboard\n        </a>\n      </td>\n    </tr>\n  </tbody>\n</table>"
     },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(rate({container_name=~\"$service\", level=~\"$level_filter\"} |~ `.*$search_message.*` [$__auto]))",
       "legendFormat": "{{container_name}}"
      },
      {
       "direction": "backward",
       "expr": "sum(count_over_time({container_name=~\"$service\", level=~\"$level_filter\"} |~ `.*$search_message.*` [$__auto]))",
       "legendFormat": "{{container_name}}"
      },
      {
       "direction": "backward",
       "expr": "count(sum(count_over_time({container_name=~\"$service\", level=~\"$level_filter\"} |~ `.*$search_message.*` [$__auto])) by(container_name))",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "type": "logs",
     "gridPos": { "h": 9, "w": 20, "x": 4, "y": 2 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{container_name=~\"$service\", level=~\"$level_filter\"} |~ `.*$search_message.*` | pattern `<message>` | line_format \"[{{.container_name}}] {{.message}}\"",
       "legendFormat": "{{message}}"
      }
     ]
    },
    { "title": "Select Severity", "type": "volkovlabs-variable-panel", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 } },
    { "title": "Search Message", "type": "volkovlabs-variable-panel", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 } }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory Usage: All Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(name) (container_memory_usage_bytes)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage: $service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"$service\"}",
     "legendFormat": "Usage: {{name}}"
    },
    {
     "expr": "container_memory_working_set_bytes{name=\"$service\"}",
     "legendFormat": "Working Set: {{name}}"
    },
    {
     "expr": "container_spec_memory_limit_bytes{hostname=\"$service\"} > 0",
     "legendFormat": "Limit: {{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage: PVE",
   "type": "timeseries",
   "description": "Total time in seconds that processes have waited for CPU time\t",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "hardware_memory_usage_ratio", "legendFormat": "Memory Usage: {{hostname}}" },
    {
     "expr": "increase(hardware_pressure_memory_seconds_total[1h])",
     "legendFormat": "Memory Pressure: {{hostname}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU Usage: All Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total[10m]) * 100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage: $service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"$service\"}[10m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Pressure: PVE",
   "type": "timeseries",
   "description": "Total time in seconds that processes have waited for CPU time\t",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(hardware_pressure_cpu_seconds_total[10m])",
     "legendFormat": "CPU Usage: {{hostname}}"
    }
   ]
  },
  {
   "title": "CPU Usage: All Services",
   "type": "timeseries",
   "description": "Usage > 100%",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name) (\n    rate(container_cpu_usage_seconds_total[10m]) * 100\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Reads: All Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(device, name)(\n  rate(container_fs_reads_bytes_total[10m])\n) > 0",
     "legendFormat": "{{name}} ({{device}})"
    }
   ]
  },
  {
   "title": "Reads: $service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_fs_reads_bytes_total{name=\"$service\"}[10m]) > 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Writes: All Services",
   "type": "timeseries",
   "description": "Writes > 30 KiB/s",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(device, name) (\n    rate(container_fs_writes_bytes_total[10m])\n) > 0",
     "legendFormat": "{{name}} ({{device}})"
    }
   ]
  },
  {
   "title": "Writes: $service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_fs_writes_bytes_total{name=\"$service\"}[10m]) > 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Received Network Traffic: All Services",
   "type": "timeseries",
   "description": "Received > 30 MiB/s",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(name) (\n    rate(container_network_receive_bytes_total[10m])\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic: $service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{name=\"$service\"}[10m]) > 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic: All Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(name) (\n    rate(container_network_transmit_bytes_total[10m])\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic: $service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{name=\"$service\"}[10m]) > 0)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}