{
 "title": "o11y-service-health",
 "tags": [
  "owner:srp",
  "status:production"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics_datasource", "label": "Metrics Datasource", "query": "prometheus" },
   { "name": "logs_datasource", "label": "Logs Datasource", "query": "loki" },
   { "name": "cluster", "label": "Site", "query": { "query": "query_result(cw_sot_site_info)" } },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(container_last_seen{cluster=\"$cluster\", container_label_com_docker_compose_project=\"echo\"},container_label_com_docker_compose_service)"
    }
   },
   {
    "name": "service_filter",
    "query": {
     "query": "label_values(container_last_seen{cluster=\"$cluster\", container_label_com_docker_compose_project=\"echo\"},container_label_com_docker_compose_service)"
    }
   },
   { "name": "search_message" },
   {
    "name": "level_filter",
    "query": {}
   },
   {
    "name": "site_tags",
    "query": {
     "query": "label_values(cw_sot_site_info{cluster=\"$cluster\"},tags)"
    }
   }
  ]
 },
 "panels": [
  { "title": "ECHO Service Health Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": {
    "content": "<table>\n  <tbody style=\"font-family: 'Roboto Mono', monospace; font-size: 0.75rem\">\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Service</td>\n      <td>{{data.0.hostname}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Image</td>\n      <td>{{data.0.image}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Image Source</td>\n      <td>{{data.0.container_label_org_opencontainers_image_source}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">App/Stack</td>\n      <td>{{data.0.container_label_org_app}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Role</td>\n      <td>{{data.0.container_label_org_role}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Kind</td>\n      <td>{{data.0.container_label_org_kind}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Team</td>\n      <td>{{data.0.container_label_org_team}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Server</td>\n      <td>{{data.0.server}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Health</td>\n      <td style=\"color: {{#if (eq data.0.health_check '0')}}#4CAF50{{else}}#F44336{{/if}}\">\n        {{#if (eq data.0.health_check '0')}}Healthy{{else}}Unhealthy{{/if}}\n      </td>\n    </tr>\n  </tbody>\n</table>"
   },
   "targets": [
    {
     "expr": "container_last_seen{cluster=~\".+-network\", container_label_com_docker_compose_service=\"$service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "echo_health_result_code{cluster=~\".+-network\", hostname=\"$service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Health",
   "type": "table",
   "description": "Services health and operational information. The links take you to a more detailed service dashboard, and the status codes are as follows:\n\n- **OK:** Request succeeded (even with HTTP errors).\n- **RSM:** Body mismatch with `response_string_match`.\n- **BRE:** Failed to read body, invalid UTF-8, or oversized response.\n- **CNF:** General network connection failure.\n- **TO:** Request timed out.\n- **DNS:** DNS resolution error.\n- **SCM:** Status code mismatch with expected value.\n\nPolling interval by default is 10s. [Learn more in the Telegraf HTTP Response Input Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http_response)",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (cluster, hostname, server) (echo_health_result_code{cluster=~\"$cluster\", hostname!=\"\", hostname=\"$service\"})",
     "legendFormat": "echo-{{hostname}}"
    }
   ]
  },
  {
   "title": "State Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(cluster, name) (echo_server_service_running_container_sum{cluster=\"$cluster\", health=\"healthy\", name=\"$service\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ECHO Stack Uptime",
   "type": "table",
   "description": "Determined by _consul_ uptime.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum by(instance) (\n        (time() - container_start_time_seconds{cluster=\"$cluster\", hostname=\"$service\"})\n    ),\n    \"instance\",\n    \"$1\",\n    \"instance\",\n    \"(.+):.+\"\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": {
    "content": "<table>\n  <tbody style=\"font-family: 'Roboto Mono', monospace; font-size: 0.75rem\">\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Log Count</td>\n      <td>{{log_count}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Log Rate (log/s)</td>\n      <td>{{log_rate}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Service Logs</td>\n      <td>\n        <a style=\"color: #6e9fff\" ;\n          href=\"https://grafana.int.coreweave.com/d/ee2kn1qtyfldse/services-log-explorer?orgId=1&var-cluster={{ variable \"cluster\" }}&var-container_name={{ variable \"service\" }}\">\n          Dashboard\n        </a>\n      </td>\n    </tr>\n  </tbody>\n</table>"
   },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({org_id=\"network-services\", team=\"network-development\", container_name=~\"$service\", level=~\"$level_filter\", cluster=~\"$cluster\"} |~ `.*$search_message.*` [$__auto]))"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({org_id=\"network-services\", team=\"network-development\", container_name=~\"$service\", level=~\"$level_filter\", cluster=~\"$cluster\"} |~ `.*$search_message.*` [$__auto]))"
    },
    {
     "direction": "backward",
     "expr": "count(sum(count_over_time({org_id=\"network-services\", team=\"network-development\", container_name=~\"$service\", level=~\"$level_filter\", cluster=~\"$cluster\"} |~ `.*$search_message.*` [$__auto])) by(container_name))"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{org_id=\"network-services\", team=\"network-development\", container_name=~\"$service\", level=~\"$level_filter\", cluster=~\"$cluster\"} |~ `.*$search_message.*` | pattern `<message>` | line_format \"[{{.container_name}}] {{.message}}\"",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "Select Severity",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Search Message",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory: $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage: All Services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(hostname) (container_memory_usage_bytes{cluster=\"$cluster\", hostname!=\"\"})",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Memory Usage: $service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\n    sum by(hostname, instance) (container_memory_usage_bytes{cluster=\"$cluster\", hostname=\"$service\"}),\n    \"instance\",\n    \"$1\",\n    \"instance\",\n    \"(.+):.+\"\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage: ZTP Node",
     "type": "timeseries",
     "description": "Total time in seconds that processes have waited for CPU time\t",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "hardware_memory_usage_ratio{cluster=\"$cluster\", hostname=~\".*metal-ztp01-.+\"}",
       "legendFormat": "Memory Usage: {{hostname}}"
      },
      {
       "expr": "increase(hardware_pressure_memory_seconds_total{cluster=\"$cluster\", hostname=~\".*metal-ztp01-.+\"}[1h])",
       "legendFormat": "Memory Pressure: {{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU: $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage: All Services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by(hostname) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", hostname!=\"\", container_label_com_docker_compose_project=\"echo\"}[10m]) * 100)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "CPU Usage: $service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "label_replace(\n    sum by(hostname,instance) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", hostname=\"$service\", container_label_com_docker_compose_project=\"echo\"}[10m]) * 100),\n    \"instance\",\n    \"$1\",\n    \"instance\",\n    \"(.+):.+\"\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Pressure: ZTP Node",
     "type": "timeseries",
     "description": "Total time in seconds that processes have waited for CPU time\t",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "increase(hardware_pressure_cpu_seconds_total{cluster=\"$cluster\", hostname=~\".*metal-ztp01-.+\"}[10m])",
       "legendFormat": "CPU Usage: {{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ECHO Stack Health Summary: $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Site Details",
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": {
      "content": "<table>\n  <tbody style=\"font-family: 'Roboto Mono', monospace; font-size: 0.8rem\">\n    {{#if (eq group NULL)}}\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Zone</td>\n      <td>{{name}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Geo / Super Region / Region</td>\n      <td>{{geo}} / {{super_region}} / {{region}}</td>\n    </tr>\n    {{else}}\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">{{group}}</td>\n      <td>{{name}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Geo / Super Region</td>\n      <td>{{geo}} / {{super_region}}</td>\n    </tr>\n    {{/if}}\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Locode / Facility</td>\n      <td>{{locode}} / {{facility}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Intended Status (Alert Status)</td>\n      <td style=\"color:\n        {{#if (eq intended_status '0')}}#fa96eb {{else if (eq intended_status '1')}}#4caf50 {{else if (eq\n        intended_status '2')}}#e6ed61 {{else if (eq intended_status '3')}}#edb158 {{else if (eq intended_status '4'\n        )}}#58deed {{else if (eq intended_status '5')}}#bba3f0 {{else if (eq intended_status '6')}}#bdbbbf\n        {{else}}#f44336{{/if}}\">\n        {{#if (eq intended_status '0')}}Planned\n        {{#if (eq alert_status '1')}}(enabled){{else}}(disabled){{/if}}\n        {{else if (eq intended_status '1')}}Active\n        {{#if (eq alert_status '1')}}(enabled){{else}}(disabled){{/if}}\n        {{else if (eq intended_status '2')}}Provisioned\n        {{#if (eq alert_status '1')}}(enabled){{else}}(disabled){{/if}}\n        {{else if (eq intended_status '3')}}Staged\n        {{#if (eq alert_status '1')}}(enabled){{else}}(disabled){{/if}}\n        {{else if (eq intended_status '4')}}Maintenance\n        {{#if (eq alert_status '1')}}(enabled){{else}}(disabled){{/if}}\n        {{else if (eq intended_status '5')}}Decommissioning\n        {{#if (eq alert_status '1')}}(enabled){{else}}(disabled){{/if}}\n        {{else if (eq intended_status '6')}}Inventory\n        {{#if (eq alert_status '1')}}(enabled){{else}}(disabled){{/if}}\n        {{else if (eq intended_status '7')}}Unknown (disabled)\n        {{else}}Completely Unknown ({{intended_status}})\n        {{/if}}\n      </td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Totals: circuits / devices / interfaces</td>\n      <td>{{circuit_count}} / {{device_count}} / {{interface_count}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">Tags</td>\n      <td>{{variable \"site_tags\"}}</td>\n    </tr>\n    <tr>\n      <td style=\"background-color: #2f3030; color: #B0BEC5\">NetBox ID</td>\n      <td>\n        <a style=\"color: #6e9fff\" ; href=\"https://coreweave.cloud.netboxapp.com/dcim/sites/{{netbox_id}}/\">\n          {{netbox_id}}\n        </a>\n      </td>\n    </tr>\n  </tbody>\n</table>"
     },
     "targets": [
      {
       "expr": "cw_sot_site_info{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cw_sot_site_intended_status{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cw_sot_site_alert_status{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(cw_sot_device_info{cluster=\"$cluster\"}) or 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(cw_sot_interface_info{cluster=\"$cluster\"}) or 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(cw_sot_circuit_info{cluster=\"$cluster\"}) or 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ECHO Containers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(container_last_seen{cluster=\"$cluster\", container_label_com_docker_compose_project=\"echo\"}) by (name))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service Health",
     "type": "table",
     "description": "Services health and operational information. The links take you to a more detailed service dashboard, and the status codes are as follows:\n\n- **OK:** Request succeeded (even with HTTP errors).\n- **RSM:** Body mismatch with `response_string_match`.\n- **BRE:** Failed to read body, invalid UTF-8, or oversized response.\n- **CNF:** General network connection failure.\n- **TO:** Request timed out.\n- **DNS:** DNS resolution error.\n- **SCM:** Status code mismatch with expected value.\n\nPolling interval by default is 10s. [Learn more in the Telegraf HTTP Response Input Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http_response)",
     "gridPos": { "h": 8, "w": 7, "x": 9, "y": 46 },
     "targets": [
      {
       "expr": "sum by (cluster, hostname, server) (echo_health_result_code{cluster=\"$cluster\", hostname!=\"\", external=\"false\"})",
       "legendFormat": "echo-{{hostname}}"
      },
      {
       "expr": "sum by(cluster, hostname, server) (echo_health_result_code{cluster=\"$cluster\", hostname!=\"\", external=\"false\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_replace(\n    sum by(cluster, hostname, name) (\n        (time() - container_start_time_seconds{cluster=\"$cluster\", hostname!=\"\", container_label_com_docker_compose_project=\"echo\"})/3600\n    ),\n    \"hostname\",\n    \"$2\",\n    \"container_label_com_docker_compose_service\",\n    \"(^echo-?(echo-?).*)\"\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unhealthy ECHO Services",
     "type": "table",
     "description": "Services health and operational information. The links take you to a more detailed service dashboard, and the status codes are as follows:\n\n- **OK:** Request succeeded (even with HTTP errors).\n- **RSM:** Body mismatch with `response_string_match`.\n- **BRE:** Failed to read body, invalid UTF-8, or oversized response.\n- **CNF:** General network connection failure.\n- **TO:** Request timed out.\n- **DNS:** DNS resolution error.\n- **SCM:** Status code mismatch with expected value.\n\nPolling interval by default is 10s. [Learn more in the Telegraf HTTP Response Input Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http_response)",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 46 },
     "targets": [
      {
       "expr": "echo_server_service_running_container_sum{cluster=\"$cluster\", health=\"healthy\"} == 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Restarting Services",
     "type": "table",
     "description": "Services that have restarted 3 or more times over the last hour",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 46 },
     "targets": [
      {
       "expr": "sort_desc(count by(cluster, name) (count_over_time(container_last_seen{cluster=\"$cluster\", name=~\".+\", container_label_com_docker_compose_project=\"echo\"}[1h]))) >= 4",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Non-ECHO Containers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(container_last_seen{cluster=\"$cluster\", container_label_com_docker_compose_project!=\"echo\"}) by (name))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ECHO Service Outliers: All Sites",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filter by Service",
     "type": "volkovlabs-variable-panel",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Memory Usage: All Services",
     "type": "timeseries",
     "description": "Usage > 30 GiB/s",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "sum by(hostname, cluster) (\n    label_replace(\n        container_memory_usage_bytes{cluster=~\".+-network\", hostname!=\"\", hostname=~\"$service_filter\", container_label_com_docker_compose_project=\"echo\"} /1024 /1024,\n        \"cluster\", \"$1\", \"cluster\", \"^(.*)-network$\"\n    )\n) > 30000",
       "legendFormat": "{{hostname}} ({{cluster}})"
      }
     ]
    },
    {
     "title": "CPU Usage: All Services",
     "type": "timeseries",
     "description": "Usage > 100%",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by(hostname, cluster) (\n    label_replace(\n        rate(container_cpu_usage_seconds_total{cluster=~\".+-network\", hostname!=\"\", hostname=~\"$service_filter\", container_label_com_docker_compose_project=\"echo\"}[10m]) * 100,\n        \"cluster\", \"$1\", \"cluster\", \"(.*)-network$\"\n    )\n) > 100",
       "legendFormat": "{{hostname}} ({{cluster}})"
      }
     ]
    },
    {
     "title": "Reads: All Services",
     "type": "timeseries",
     "description": "Reads > 30 KiB/s",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(hostname, cluster) (\n    label_replace(\n        rate(container_fs_reads_bytes_total{cluster=~\".+-network\", hostname!=\"\", hostname=~\"$service_filter\", container_label_com_docker_compose_project=\"echo\"}[10m]),\n        \"cluster\", \"$1\", \"cluster\", \"(.*)-network$\"\n    )\n) > 30000",
       "legendFormat": "{{hostname}} ({{cluster}})"
      }
     ]
    },
    {
     "title": "Writes: All Services",
     "type": "timeseries",
     "description": "Writes > 30 KiB/s",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(hostname, cluster) (\n    label_replace(\n        rate(container_fs_writes_bytes_total{cluster=~\".+-network\", hostname!=\"\", hostname=~\"$service_filter\", container_label_com_docker_compose_project=\"echo\"}[10m]),\n        \"cluster\", \"$1\", \"cluster\", \"(.*)-network$\"\n    )\n) > 30000000",
       "legendFormat": "{{hostname}} ({{cluster}})"
      }
     ]
    },
    {
     "title": "Received Network Traffic: All Services",
     "type": "timeseries",
     "description": "Received > 30 MiB/s",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(hostname, cluster) (\n    label_replace(\n        rate(container_network_receive_bytes_total{cluster=~\".+-network\", hostname!=\"\", hostname=~\"$service_filter\", container_label_com_docker_compose_project=\"echo\"}[10m]),\n        \"cluster\", \"$1\", \"cluster\", \"(.*)-network$\"\n    )\n) > 30000000",
       "legendFormat": "{{hostname}} ({{cluster}})"
      }
     ]
    },
    {
     "title": "Sent Network Traffic: All Services",
     "type": "timeseries",
     "description": "Sent > 30 MiB/s",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(hostname, cluster) (\n    label_replace(\n        rate(container_network_transmit_bytes_total{cluster=~\".+-network\", hostname!=\"\", hostname=~\"$service_filter\", container_label_com_docker_compose_project=\"echo\"}[10m]),\n        \"cluster\", \"$1\", \"cluster\", \"(.*)-network$\"\n    )\n) > 30000000",
       "legendFormat": "{{hostname}} ({{cluster}})"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O: $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reads: All Services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (hostname) (rate(container_fs_reads_bytes_total{cluster=~\"$cluster\", hostname!=\"\", container_label_com_docker_compose_project=\"echo\"}[10m]) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Reads: $service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (hostname) (rate(container_fs_reads_bytes_total{cluster=~\"$cluster\", hostname=\"$service\", container_label_com_docker_compose_project=\"echo\"}[10m]) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Writes: All Services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (hostname) (rate(container_fs_writes_bytes_total{cluster=~\"$cluster\", hostname!=\"\", container_label_com_docker_compose_project=\"echo\"}[10m]) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Writes: $service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (hostname) (rate(container_fs_writes_bytes_total{cluster=~\"$cluster\", hostname=\"$service\", container_label_com_docker_compose_project=\"echo\"}[10m]) > 0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network: $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Network Traffic: All Services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (hostname) (rate(container_network_receive_bytes_total{cluster=~\"$cluster\", hostname!=\"\", container_label_com_docker_compose_project=\"echo\"}[10m]) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Received Network Traffic: $service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (hostname) (rate(container_network_receive_bytes_total{cluster=~\"$cluster\", hostname=\"$service\", container_label_com_docker_compose_project=\"echo\"}[10m]) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sent Network Traffic: All Services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (hostname) (rate(container_network_transmit_bytes_total{cluster=~\"$cluster\", hostname!=\"\", container_label_com_docker_compose_project=\"echo\"}[10m]) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sent Network Traffic: $service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (hostname) (rate(container_network_transmit_bytes_total{cluster=~\"$cluster\", hostname=\"$service\", container_label_com_docker_compose_project=\"echo\"}[10m]) > 0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}