
- job_name: victoria-metrics
  scrape_interval: 1m
  scrape_timeout: 20s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
        - "victoria-metrics:8428"
  relabel_configs:
    - target_label: stack
      replacement: o11y-home

- job_name: grafana
  scrape_interval: 1m
  scrape_timeout: 20s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
        - "grafana:3000"
  relabel_configs:
    - target_label: stack
      replacement: o11y-home

- job_name: loki
  scrape_interval: 1m
  scrape_timeout: 20s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
        - "loki:3001"
  relabel_configs:
    - target_label: stack
      replacement: o11y-home

- job_name: pve-exporter
  scrape_interval: 1m
  scrape_timeout: 20s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
        - "pve-exporter:9221"
  relabel_configs:
    - target_label: stack
      replacement: o11y-home

- job_name: pve
  scrape_interval: 1m
  scrape_timeout: 20s
  static_configs:
    - targets:
        - "10.10.10.100"  # o11y node
  metrics_path: /pve
  params:
    module: [default]
  relabel_configs:
    - target_label: stack
      replacement: o11y-home
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: pve-exporter:9221

- job_name: air-gradient
  scrape_interval: 1m
  scrape_timeout: 20s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
        - "172.16.100.146:80"
  relabel_configs:
    - target_label: stack
      replacement: o11y-home

- job_name: cadvisor
  scrape_interval: 1m
  scrape_timeout: 20s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
        - "cadvisor:8080"
  relabel_configs:
    - target_label: stack
      replacement: o11y-home
